services:
  spaceboot:
    environment:
      - JAVA_TOOL_OPTIONS=
        -DsocksProxyHost=host.docker.internal
        -DsocksProxyPort=4140
        -Djavax.net.ssl.trustStore=/etc/ssl/speedscale/jks/cacerts.jks
        -Djavax.net.ssl.trustStorePassword=changeit
    image: gcr.io/speedscale-demos/spaceboot:latest
    ports:
      - 8080:8080
    volumes:
      - ${HOME}/.speedscale/certs:/etc/ssl/speedscale/jks
