networks:
  speedscale-responder-net:
    driver: bridge
services:
  spaceboot:
    environment:
      - JAVA_TOOL_OPTIONS=
        -Djavax.net.ssl.trustStore=/etc/ssl/speedscale/jks/cacerts.jks
        -Djavax.net.ssl.trustStorePassword=changeit
    image: gcr.io/speedscale-demos/spaceboot:latest
    ports:
      - 8080:8080
    volumes:
      - ${HOME}/.speedscale/certs:/etc/ssl/speedscale/jks
    networks:
    - speedscale-responder-net
  responder:
    environment:
    - SPEEDSCALE_CONFIG_YAML=/config.yaml
    - REDIS_SERVICE_HOST=redis
    - REDIS_SERVICE_PORT=6379
    - SERVICE_HTTPS_PORT=443
    - SERVICE_HTTP_PORT=80
    # https://app.speedscale.com/config
    - TEST_CONFIG_ID=standard
    # snapshot to source requests from
    - SNAPSHOT_ID=cf3fab26-73cd-4921-9b47-18d22acd53c4
    image: gcr.io/speedscale/responder:v1.3.405
    restart: always
    volumes:
    - ${HOME}/.speedscale/certs:/etc/ssl/speedscale
    - ${HOME}/.speedscale/config.yaml:/config.yaml
    networks:
      speedscale-responder-net:
        aliases:
        - api.spacexdata.com
        - api.fiscaldata.treasury.gov
  redis:
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_AOF_ENABLED=no
    image: gcr.io/speedscale/redis
    ports:
    - 6379:6379
    restart: always
    networks:
    - speedscale-responder-net
