services:
  spaceboot:
    environment:
      - JAVA_TOOL_OPTIONS=
        -Dspring.profiles.active=integration
    image: gcr.io/speedscale-demos/spaceboot:latest
    ports:
      - 8080:8080
  wiremock:
    image: wiremock/wiremock:3.1.0
    volumes:
      - $PWD/src/test/resources:/home/wiremock
